### ISSUE TITLE
lib/router/index.js:458:13 ....nodemon is crashing

### ISSUE THREAD

**Issue by isaac8069** [WDI-SEA/project-2-issues#1]
<img width="558" alt="Screen Shot 2021-11-15 at 9 26 51 AM" src="https://user-images.githubusercontent.com/90520586/141800668-b01f7665-76fa-44a0-b2c9-313bb60260fe.png">

**Comment by DoireannJane** [comment]
Are all your routes being exported?

**Comment by DoireannJane** [comment]
Is this issue resolved?

**Comment by isaac8069** [comment]
Still working on it.

**Comment by isaac8069** [comment]
Working on it via another issues thread. Closing this one out
