### ISSUE TITLE
Attempting to add new column to existing table.

### ISSUE THREAD

**Issue by steven43533** [WDI-SEA/project-2-issues#11]
While working on the project I realized I am going to need to store the animeId within my database but failed to create a animeId key in my DB when I initially created my DB. Now I am having trouble adding a new column to the existing table I have(I don't want to drop it and start anew). I've now watched a couple of youtube videos on it and stackoverflow threads but for some reason when I db:migrate it won't actually update my table(using pgadmin to view).

![Screen Shot 2021-11-15 at 1 01 35 PM](https://user-images.githubusercontent.com/24616638/141831538-54862c21-87d1-4acc-998e-9e0ec07386f3.png)

![Screen Shot 2021-11-15 at 1 02 00 PM](https://user-images.githubusercontent.com/24616638/141831589-1284a160-dfb0-4b19-ad27-0627c3199f29.png)

**Comment by DoireannJane** [comment]
What does your db look like? Did you say you weren't able to alter it and add a new column?
