### ISSUE TITLE
auth

### ISSUE THREAD

**Issue by galyverasi** [WDI-SEA/project-2-issues#13]
I've cleared my users table in psql to start over and when I'm making signing up for a new account shouldn't it revert to id: 1 instead it gave me id:2 in psql

  2 | Galyver | galyverasi@gmail.com | 12345678 | 2021-11-15 11:54:07.673-07 | 2021-11-15 11:54:07.673-07

also it gave my "unauthorized" in my localhost

I've dropped my users model. Recreate it and migrate again

**Comment by tkolsrud** [comment]
Postgres will always create a new primary key, even if the previous key's data has been dropped, assigning it to 2 is normal behavior. Could you elaborate on the "unauthorized" issue/post a screenshot of the error?

**Comment by galyverasi** [comment]
The unauthorized error page went away BUT
Is there a way to "reset" my auth? When I login it says:
Invalid username and/or password.

**Comment by tkolsrud** [comment]
I think you'd have to do that manually using the database, but you could also just go check and see what it has under username and password for your user

**Comment by galyverasi** [comment]
my email/password is exactly how it's shown in the database so I don't understand why it's giving me invalid
