### ISSUE TITLE
Calling API

### ISSUE THREAD

**Issue by LindZCoding** [WDI-SEA/project-2-issues#18]
Honestly I feel super lost and feel like I have no idea what I am doing. I am having trouble calling my API.

MyAnimeList = https://myanimelist.net/clubs.php?cid=13727

I registered and got a client ID. I think I am just confused on how to connect everything and I have tried looking back on our code alongs and still struggling.

```app.get('/', (req, res) => {
    let animeUrl = 'https://myanimelist.net/v1/oauth2/authorize?';
    // Use request to call the API
    axios.get(animeUrl)```

I think it is something like this.

**Comment by DoireannJane** [comment]
How is the new Anime API going? Are your routes and views all set up?

**Comment by LindZCoding** [comment]
> How is the new Anime API going? Are your routes and views all set up?

I am trying to set them up right now...

**Comment by LindZCoding** [comment]
> How is the new Anime API going? Are your routes and views all set up?

would you be able to help me with that a bit? Just to make sure I am on the right track

**Comment by DoireannJane** [comment]
Hi Lindsay! Sure. Is there something in particular you are unsure of?
