### ISSUE TITLE
authorization header

### ISSUE THREAD

**Issue by paulinal3** [WDI-SEA/project-2-issues#19]
The other API I'm using says it "requires a token to be sent in as an authorization header"
Exact format for sending token: 
```
{ authorization: Token_<token goes here> }
```
And the docs don't show anything about adding the token at the end of the api url so where would I put the authorization header? Does it go before every axios call or at the top of the page? I have the token already saved in my .env

The code below is what I've tried but nodemon keeps spitting out a really long chunk of code and ending with saying `[nodemon] app crashed - waiting for file changes before starting...` 
```js
router.get('/results', (req, res) => {
    {authorization: process.env.API_KEY}
    const rootApi = 'https://v1.exercisedb.io/api/exercises'
    let muscleTargeted = req.query.bodyPart

    axios.get(`${rootApi}/bodyPart/${muscleTargeted}`)
    .then(apiRes => {
        console.log('this is the apiRes', apiRes.data)
    })
})
```

Also wondering if someone can just take a look at my ERD a second time to make sure it makes sense.

**Comment by tkolsrud** [comment]
Here's  sample of the syntax:
https://www.codegrepper.com/code-examples/javascript/axios+post+request+send+bearer+token

**Comment by tkolsrud** [comment]
You've got the right idea, you just need to put that authorization object in the axios.get after the url

**Comment by paulinal3** [comment]
Oh my bad!! Sorry I was able to figure that part out! Now I only need someone to talk through my ERD to make sure it's right before I start creating models

**Comment by tkolsrud** [comment]
Oh good! Why don't you open a new request with a screenshot of the erd that way everyone can get eyes on it
