### ISSUE TITLE
Grammatical issue (extra bracket)

### ISSUE THREAD

**Issue by Eddycodes27** [WDI-SEA/project-2-issues#20]
I am getting an error due to a supposed extra bracket.

**Comment by tkolsrud** [comment]
The worst. Still looking for that bracket?

**Comment by tkolsrud** [comment]
Hey eddy can you open a new issue with a screen shot of your foods route? That way Timm and doireanne can get eyes on it

**Comment by Eddycodes27** [comment]
Ok, new issue opened.
