### ISSUE TITLE
Cannot seem to target API data on specific query

### ISSUE THREAD

**Issue by harrdev** [WDI-SEA/project-2-issues#22]
Similar to the OMDB project;  where a link is generated from the list of searches, and each movie is a clickable link that takes you to a detail page to drill down for more details/options.  

My issue is that after the data that is displayed is passed back to a axios call to get more details, I don't seem to be able to access data within that object in the API.

I'm lost.

**Comment by tkolsrud** [comment]
Are you getting a response with an object you can't access, or just nothing at all?

**Comment by harrdev** [comment]
I'm getting access to the object, but having a hard time drilling down to what I need in an array within that object

**Comment by harrdev** [comment]
Timm is a god.  Issue was stringified data being passed to end of URL with quotes on it, therefor not resulting in the correct endpoint.
