### ISSUE TITLE
Sign Up is not working/Log In

### ISSUE THREAD

**Issue by isaac8069** [WDI-SEA/project-2-issues#24]
When I enter the information and hit sign up, it clears out the information

**Comment by tkolsrud** [comment]
are you getting any errors in the console?

**Comment by isaac8069** [comment]
column Id does not exist

**Comment by tkolsrud** [comment]
Have you done a 
` sequelize db: migrate`
yet?

**Comment by isaac8069** [comment]
Yes I have

**Comment by TaylorDarneille** [comment]
Can you post the whole output?

**Comment by TaylorDarneille** [comment]
(I'm looking for casing)

**Comment by TaylorDarneille** [comment]
resolved! 
Next steps:

1. implement all your CRUDing of apartments and tags
2. Set up cloudinary API
3. THEN you can worry about it looking pretty
