### ISSUE TITLE
Having issues implementing Cloudinary API

### ISSUE THREAD

**Issue by isaac8069** [WDI-SEA/project-2-issues#26]
I feel like I have no idea what I am doing. I am having trouble calling my API. Maybe I am not understanding how to incorporate it into my controllers

**Comment by tkolsrud** [comment]
can you send a screenshot of the api request in your controller?

**Comment by TaylorDarneille** [comment]
Have you read the documentation?

**Comment by TaylorDarneille** [comment]
open again when your crudding is complete :)
