### ISSUE TITLE
Trying to get multiple results to fill an index page

### ISSUE THREAD

**Issue by LindZCoding** [WDI-SEA/project-2-issues#27]
```app.get('/', (req, res)=>{
    let base_url = "https://api.jikan.moe/v3/anime"

    axios.get("https://api.jikan.moe/v3/anime/")
    .then(res => console.log(res.data))
    // .then(data => console.log(data))
    .catch(err => console.error)
    res.render('home')
})```

**Comment by tkolsrud** [comment]
Have you tried throwing in one of the broader parameters, like "movie" ?

**Comment by TaylorDarneille** [comment]
Your `res.render()` needs to be inside your `.then`

**Comment by LindZCoding** [comment]
> Have you tried throwing in one of the broader parameters, like "movie" ?

I decided I think it will be better for the user to do a search on an anime or genre they are looking for since there is way too many to show
