### ISSUE TITLE
hashing password in seeder file

### ISSUE THREAD

**Issue by mgkdn9** [WDI-SEA/project-2-issues#28]
I had it working but then changed "'password'" into "bcrypt.hash('password',10)" and now getting error message: "ERROR: Invalid value Promise { <pending> }"
Users-MBP:express-auth-reference user$ sequelize db:seed:all

Sequelize CLI [Node: 17.0.1, CLI: 6.3.0, ORM: 6.3.5]

Loaded configuration file "config/config.json".
Using environment "development".
== 20211116042729-demo-users: migrating =======

ERROR: Invalid value Promise { <pending> }

```js
'use strict';
const bcrypt = require('bcrypt');
module.exports = {
  up: (queryInterface, Sequelize) => {
      return queryInterface.bulkInsert('users', [{
        name: 'Mike',
        phone: '3146986241',
        email: 'mkohlberg95@gmail.com',
        password: bcrypt.hash('password',10),
        latitude: '38.509930',
        longitude: '-90.473488',
        createdAt: new Date(),
        updatedAt: new Date()
      }], {});
  },
  down: (queryInterface, Sequelize) => {
      return queryInterface.bulkDelete('users', null, {});
  }
};`

**Comment by TaylorDarneille** [comment]
The sequelize hook hashes the password already, then replaces the value of `password` with the hash. Is there a reason you wanted to change it?

**Comment by TaylorDarneille** [comment]
Oh I just registered that this is a seeder file

**Comment by TaylorDarneille** [comment]
You need to hash it before you place it in the object

**Comment by tkolsrud** [comment]
Hey mike, did you ever resolve this issue?

**Comment by mgkdn9** [comment]
I am actually still having problems with this
