### ISSUE TITLE
need to add attribute to table

### ISSUE THREAD

**Issue by hannahlegros** [WDI-SEA/project-2-issues#30]
I have already migrated my tables, but I realized I need to add an attribute to one of my tables. I'm afraid I'm going to screw up my database... Just need help walking through the steps so I don't create a bigger issue.

**Comment by TaylorDarneille** [comment]
1. sequelize db:migrate:undo:all
2. add the field to your model file
3. add the field to your migrations file
4. sequelize db:migrate
5. let me know how it goes!!

**Comment by hannahlegros** [comment]
`Hannahs-MBP:express-auth-reference legros$ sequelize db:migrate:undo:all

Sequelize CLI [Node: 17.0.1, CLI: 6.3.0, ORM: 6.3.5]

Loaded configuration file "config/config.json".
Using environment "development".

ERROR: Unable to find migration: 20211114233822-create-ingredients.js

Hannahs-MBP:express-auth-reference legros$ sequelize db:migrate

Sequelize CLI [Node: 17.0.1, CLI: 6.3.0, ORM: 6.3.5]

Loaded configuration file "config/config.json".
Using environment "development".
No migrations were executed, database schema was already up to date.
Hannahs-MBP:express-auth-reference legros$ sequelize db:migrate

Sequelize CLI [Node: 17.0.1, CLI: 6.3.0, ORM: 6.3.5]

Loaded configuration file "config/config.json".
Using environment "development".
No migrations were executed, database schema was already up to date.`

This is what comes up after I followed those steps.

**Comment by hannahlegros** [comment]
Hannahs-MBP:express-auth-reference legros$ sequelize db:migrate:undo:all

Sequelize CLI [Node: 17.0.1, CLI: 6.3.0, ORM: 6.3.5]

Loaded configuration file "config/config.json".
Using environment "development".

ERROR: Unable to find migration: 20211114233822-create-ingredients.js

Hannahs-MBP:express-auth-reference legros$ sequelize db:migrate

Sequelize CLI [Node: 17.0.1, CLI: 6.3.0, ORM: 6.3.5]

Loaded configuration file "config/config.json".
Using environment "development".
No migrations were executed, database schema was already up to date.
Hannahs-MBP:express-auth-reference legros$ sequelize db:migrate

Sequelize CLI [Node: 17.0.1, CLI: 6.3.0, ORM: 6.3.5]

Loaded configuration file "config/config.json".
Using environment "development".
No migrations were executed, database schema was already up to date.

This is what comes up when I run through those commands.

**Comment by hannahlegros** [comment]
added to my recipe.js: 
`recipe.init({
    name: DataTypes.STRING,
    idDrink: DataTypes.INTEGER
}`

**Comment by hannahlegros** [comment]
and added this to my migration: 
`idDrink: {
        type: Sequelize.INTEGER
      },`

**Comment by TaylorDarneille** [comment]
ah - it needs to be drinkId

**Comment by hannahlegros** [comment]
Thanks Taylor!!

**Comment by TaylorDarneille** [comment]
Feel free to open if another issue comes up :)
