### ISSUE TITLE
I cant get my controller to create a new apartment and post it

### ISSUE THREAD

**Issue by isaac8069** [WDI-SEA/project-2-issues#31]
I enter the information and hit submit. It doesn't render anything

**Comment by TaylorDarneille** [comment]
Do you know it's hitting the correct post route? If you put a console.log in the route, does it fire?

**Comment by isaac8069** [comment]
<img width="1271" alt="Screen Shot 2021-11-16 at 2 26 14 PM" src="https://user-images.githubusercontent.com/90520586/142052108-eef7fa9d-82c5-4dcc-ace7-f6bb892b942a.png">

The create does not work. I am able to view all post. That is working fine. However, there is nothing to view because nothing has been created

**Comment by TaylorDarneille** [comment]
console.logs that you write in your route go in your terminal where nodemon is running, not the browser. Do you have a `post` route with a url pattern of `/` in your controller?

**Comment by isaac8069** [comment]
<img width="739" alt="Screen Shot 2021-11-16 at 2 36 28 PM" src="https://user-images.githubusercontent.com/90520586/142053603-e48a28c7-011c-41a8-97f8-e52aeb1f66a1.png">

this is what I get back in the terminal after logging in and trying to post an apartment listing

**Comment by isaac8069** [comment]
```js
//POST an apartment
router.post('/', (req, res) => {
    console.log('where are my apartments')
    db.apartment.create({
        title: req.body.title,
        rent: req.body.rent,
        description: req.body.description,
        location: req.body.location,
        bedroom: req.body.bedroom,
        bathroom: req.body.bathroom,
        amenity: req.body.amenity,
        roommate: req.body.roommate
        })
    .then((apartment) => {
        res.redirect('/apartments/new')
    })
    .catch((error) => {
        res.status(200).send('Post an apartment')
        })
})    
```

**Comment by TaylorDarneille** [comment]
(a) is it really the /apartments/new page really the page you want to redirect to?
(b) is it successfully redirecting?

**Comment by isaac8069** [comment]
I just tried a number of routes with Tom and nothing worked. To be honest, now I am not so sure about the routes.

**Comment by isaac8069** [comment]
Resolved!
