### ISSUE TITLE
Nested axios call

### ISSUE THREAD

**Issue by harrdev** [WDI-SEA/project-2-issues#32]
I'm looking for help trying to figure out how to do a nested axios call.  There is a URL for an API request that is returned in the original axios.get.  I need to access that url in another axios call after the original call to display a property within that second axios call.

I tried putting another axios call in a .then within the route but it didn't work.

**Comment by TaylorDarneille** [comment]
that is how you do it, so post your code here in a snippet so we can see it :)

**Comment by harrdev** [comment]
`router.get('/', isLoggedIn, (req, res) => {
    axios.all([requestOne, requestTwo, requestThree, requestFour, requestFive, requestSix, requestSeven, requestEight, requestNine]).then(axios.spread((...responses) => {
        const responseOne = responses[0]
        const responseTwo = responses[1]
        const responseThree = responses[2]
        const responseFour = responses[3]
        const responseFive = responses[4]
        const responseSix = responses[5]
        const responseSeven = responses[6]
        const responseEight = responses[7]
        const responseNine = responses[8]
        // use/access the results 
        let swPeople1 = responseOne.data.results
        let swPeople2 = responseTwo.data.results
        let swPeople3 = responseThree.data.results
        let swPeople4 = responseFour.data.results
        let swPeople5 = responseFive.data.results
        let swPeople6 = responseSix.data.results
        let swPeople7 = responseSeven.data.results
        let swPeople8 = responseEight.data.results
        let swPeople9 = responseNine.data.results
        res.render('people.ejs', { swPeople1, swPeople2, swPeople3, swPeople4, swPeople5, swPeople6, swPeople7, swPeople8, swPeople9 })
    })).catch(errors => {
        console.error
    })
})

router.get('/:person', function(req, res) {
    let person = req.params.person
    const searchUrl = `https://swapi.dev/api/people/?search=${person}`
    console.log("searchUrl: ", searchUrl)
    axios.get(`https://swapi.dev/api/people/?search=${person}`)
    .then(apiRes => {
        let name = apiRes.data.results[0].name
        console.log("name results: ", name)
        let homeworld = apiRes.data.results[0].homeworld
        console.log("homeworld: ", homeworld)
        console.log("data captured: ", name)
        res.render('academyPeople.ejs', { name })
    })
    .then(apiRes => {
        axios.get(homeworld)
        .then(apiRes => {
            console.log(homeworld)
        })
    })
})

**Comment by harrdev** [comment]
```
router.get('/:person', function(req, res) {
    let person = req.params.person
    axios.get(`https://swapi.dev/api/people/?search=${person}`)
    .then(apiRes => {
        let name = apiRes.data.results[0].name
        let homeworld = apiRes.data.results[0].homeworld
        console.log("homeworld: ", homeworld)
        res.render('academyPeople.ejs', { name })
    })
    .then(apiRes => {
        axios.get(homeworld)
        .then(apiRes => {
            console.log(homeworld)
        })
    })
})```

**Comment by harrdev** [comment]
`router.get('/', isLoggedIn, (req, res) => {
    axios.all([requestOne, requestTwo, requestThree, requestFour, requestFive, requestSix, requestSeven, requestEight, requestNine]).then(axios.spread((...responses) => {
        const responseOne = responses[0]
        const responseTwo = responses[1]
        const responseThree = responses[2]
        const responseFour = responses[3]
        const responseFive = responses[4]
        const responseSix = responses[5]
        const responseSeven = responses[6]
        const responseEight = responses[7]
        const responseNine = responses[8]
        // use/access the results 
        let swPeople1 = responseOne.data.results
        let swPeople2 = responseTwo.data.results
        let swPeople3 = responseThree.data.results
        let swPeople4 = responseFour.data.results
        let swPeople5 = responseFive.data.results
        let swPeople6 = responseSix.data.results
        let swPeople7 = responseSeven.data.results
        let swPeople8 = responseEight.data.results
        let swPeople9 = responseNine.data.results
        res.render('people.ejs', { swPeople1, swPeople2, swPeople3, swPeople4, swPeople5, swPeople6, swPeople7, swPeople8, swPeople9 })
    })).catch(errors => {
        console.error
    })
})

router.get('/:person', function(req, res) {
    let person = req.params.person
    const searchUrl = `https://swapi.dev/api/people/?search=${person}`
    console.log("searchUrl: ", searchUrl)
    axios.get(`https://swapi.dev/api/people/?search=${person}`)
    .then(apiRes => {
        let name = apiRes.data.results[0].name
        console.log("name results: ", name)
        let homeworld = apiRes.data.results[0].homeworld
        console.log("homeworld: ", homeworld)
        console.log("data captured: ", name)
        res.render('academyPeople.ejs', { name })
    })
    .then(apiRes => {
        axios.get(homeworld)
        .then(apiRes => {
            console.log(homeworld)
        })
    })
})`

**Comment by harrdev** [comment]
I don't know how to pass that variable homeworld into the second axios call.  It is created from the first call, it is a URL to another API resource that I need to access to extract data out of itl.
