### ISSUE TITLE
Want to add player and game associations to join table, have both IDs but not sure how to insert into table. 

### ISSUE THREAD

**Issue by DG-98** [WDI-SEA/project-2-issues#34]
![image](https://user-images.githubusercontent.com/85405879/142065377-043a9a31-70e1-4dee-b7de-07c0acea9bbe.png)

**Comment by tkolsrud** [comment]
Hey Derrick, can you post a picture of your erd?

**Comment by DG-98** [comment]
![image](https://user-images.githubusercontent.com/85405879/142068706-81a0cdd8-526d-430b-ad01-d444ac59bf91.png)

**Comment by DG-98** [comment]
It may me good to mention that Tom and I considered that the games table may not be needed since the info in that table can be pulled directly from the API, im just not sure how I'd tackle the comments going forward.

**Comment by TaylorDarneille** [comment]
You do need the games table because those are the ones that users save. Your ERD is correct as far as I'm seeing. Have you reviewed the sequelize N:M notes?

**Comment by DG-98** [comment]
im still a bit confused on how exactly to insert the data into the tables. 
![image](https://user-images.githubusercontent.com/85405879/142273962-8f63ed3e-f9db-4b39-9f16-04a5b82f9fac.png)
I'm not sure if you can insert into 2 dbs in the same post. Also unsure about my use of findOrCreate, I was thinking that by using it, I'd avoid having repeat games unless I should just go with .create and have multiples of the game for each time it's added.

**Comment by timmshinbone** [comment]
Are you still working on this? if not close it, if so, update us
