### ISSUE TITLE
Was able to render a list on results page but with no api info showing up.

### ISSUE THREAD

**Issue by kellylarrea** [WDI-SEA/project-2-issues#35]
I was able to render my results to the page but on my page I'm only getting this to show up.

![Screen Shot 2021-11-16 at 4 27 51 PM](https://user-images.githubusercontent.com/34468962/142068644-9cdecac1-bc45-4676-b609-4f6c120d7e07.png)

I'm not sure what this means and what is it telling me that I'm doing wrong.

**Comment by DoireannJane** [comment]
Have you tried console.logging that data?

**Comment by kellylarrea** [comment]
I was able to get a list to show up but now when i click on the link i get 

Cannot GET /results/[object%20Object]

**Comment by kellylarrea** [comment]
I was able to get a list to show up by editing my line of code to 

```<ul>
        <%results.forEach(function(result){%>
            <li>
                <a href="/results/<%=result.recipe.label%>"><%=result.recipe.label%></a>
            </li>
            <%})%>
    </ul>    
<%}%>```
