### ISSUE TITLE
Unable to locate ejs page via app

### ISSUE THREAD

**Issue by Eddycodes27** [WDI-SEA/project-2-issues#43]
Moved an ejs file from views to another folder inside views. Unable to locate on website.

**Comment by timmshinbone** [comment]
show a screenshot of your files in the file pane of vsCode and share how you're trying to reference that file

**Comment by Eddycodes27** [comment]
Using the following,

![Screen Shot 2021-11-17 at 11 07 21 AM](https://user-images.githubusercontent.com/91762173/142236953-bb00376d-76e8-44ab-9e92-3d64f7a446c2.png)
'/loggers/index'

**Comment by timmshinbone** [comment]
ok now show me where you're trying to call that view

**Comment by Eddycodes27** [comment]
![Screen Shot 2021-11-17 at 11 20 57 AM](https://user-images.githubusercontent.com/91762173/142239494-64d54809-3604-4f20-90e0-9c307250dfe3.png)

**Comment by Eddycodes27** [comment]
VIEWS/users.ejs (main page or index)

**Comment by timmshinbone** [comment]
let's look in a 1:1 in a couple minutes

**Comment by Eddycodes27** [comment]
Thank you
