### ISSUE TITLE
Need a thought partner to begin setting up routes and integrating database

### ISSUE THREAD

**Issue by hectorzaragoza** [WDI-SEA/project-2-issues#44]

**Comment by DoireannJane** [comment]
Hey Hector. What is the issue you're having?

**Comment by hectorzaragoza** [comment]
I am not sure how to start my routes and then getting my api response to be stored on to a database and then how to query it.

**Comment by DoireannJane** [comment]
Let's see your ERD

**Comment by hectorzaragoza** [comment]
Can we jump into a break out room?

**Comment by DoireannJane** [comment]
_Hector is building out all views._ We will circle back after lunch.

**Comment by DoireannJane** [comment]
How did the views turn out?

**Comment by hectorzaragoza** [comment]
Making progress!
