### ISSUE TITLE
trouble adding column to table

### ISSUE THREAD

**Issue by mgkdn9** [WDI-SEA/project-2-issues#47]
I need to add a 'title' column to 'toolRequests' table.
So far I have changed the migrations file, the model file, db:migrate:undo, db:migrate.
But (a) the tables were not dropped as expected(all users and toolRequest data persists) and (b) column not added to 'toolRequests'

**Comment by mgkdn9** [comment]
I did DROP TABLE "toolRequests"; so now toolRequests is gone but db:migrate doesn't recreate it

**Comment by TaylorDarneille** [comment]
resolved
