### ISSUE TITLE
browser keeps "thinking"

### ISSUE THREAD

**Issue by Mackmiller** [WDI-SEA/project-2-issues#48]
Initially "add to favorites" was redirecting to the /favorites url. I now do NOT want any redirect after the "add to favorites" button is clicked. The following code does this exactly (still adds favorite to dt without redirecting) but I noticed that the browser circle continues to spin/think after clicking the button. Other than that, it all worked great. Is there some way to stop this "browser thinking"?  I'm specifically talking about the last bit of code below. I also tried taking out that entire last .then.

```
//Creates a new favorite track
router.post('/', (req, res) => {
    const data = JSON.parse(JSON.stringify(req.body))
    //console.log('this is data', data)

    db.user.findOne({
        where: {name: req.user.name}
    })
    .then(foundUser=> {
        //console.log("adding favorite to this user:", foundUser.name)
        foundUser.createFavorite({
            trackName: data.name,
            trackLink: data.link
        }).then(fav=>{
            console.log('db instance created: \n', fav)
            //disable redirect back to favorites url
            //res.redirect("/favorites")
        });
    })
})
```

**Comment by Mackmiller** [comment]
and here is the ejs form that is using that submit button:
```
 <form method="POST" action="/favorites">
              <input hidden type="text" name="name" value="<%= name %>">
              <input hidden type="text" name="link" value="<%= spotifyLink %>">
              <button id="favorite-button" type="submit">Add to Favorites</button>
 </form>
```

**Comment by mgkdn9** [comment]
I don't think you can just sit in a POST route. maybe that's not correct but you need some kind of response (res.render, res.status, res.redirect)

**Comment by TaylorDarneille** [comment]
this is correct - you need a res.redirect

**Comment by Mackmiller** [comment]
okay, thanks! I'll figure something else out.
