### ISSUE TITLE
Help with Post route

### ISSUE THREAD

**Issue by hannahlegros** [WDI-SEA/project-2-issues#50]
Keep getting error 'Cannot POST /drinksByName/myLoveIt/addLoveIt'
Been staring at it too long. haven't add a res.redirect bc I'm not even getting the console.log.
`router.post('/addLoveIt', (req, res) => {
    const data = JSON.parse(JSON.stringify(req.body))
    console.log('this is data:', data)
    db.recipe.create({
        name: data.drinkName[0],
        drinkId: data.drinkName[1]
    })
    .then (createdFave => {
        console.log('db instance created: ', createdFave)
    })
    .catch(error => {
        console.log(error)
    })
})`

**Comment by hannahlegros** [comment]
This is the form it's pulling info from: 
`<form action="myLoveIt/addLoveIt" method="POST">
    <input hidden type="text" name="drinkName" value="<%= name %>">
    <input hidden type="text" name="drinkName" value="<%= id %>">
    <button type="submit">love it!</button>
</form>`

**Comment by hannahlegros** [comment]
This is the form: 
`// <form action="myLoveIt/addLoveIt" method="POST">
    <input hidden type="text" name="drinkName" value="<%= name %>">
    <input hidden type="text" name="drinkName" value="<%= id %>">
    <button type="submit">love it!</button>
</form>`

**Comment by tkolsrud** [comment]
Hey hannah, is there any way you can format that so it's a little more readable?

**Comment by hannahlegros** [comment]
Tom, just figured it out! Thank you!
