### ISSUE TITLE
More route issues: Cannot GET /apartments/search

### ISSUE THREAD

**Issue by isaac8069** [WDI-SEA/project-2-issues#52]

**Comment by isaac8069** [comment]
SEARCH FOR AN APARTMENT USING LOCATION

```js
router.get('/search', (req, res) => {
  //   let {term} = req.query
  //Make lowerCase
  //   term = term.toLowerCase()
  console.log(req.query)
  db.apartment.findAll({
    where: { location: req.query.location }
  }).then((apartment) => {
    res.render('apartments/result', { apartment: apartment })
  }).catch((error) => {
    console.log(error)
    res.send('display apartments')
  })
})
```

**Comment by isaac8069** [comment]
```js
<%if(apartment===undefined) {%>
    <h3>No Results Found</h3>
    <small>check your spelling and punctuation and try again</small>
    <%} else {%>
        <ul>
            <%apartments.forEach(function(apartment) {%>
                <li>
                    <a href="/apartment/<%=apartment.title%>">
                        <%=apartment.title%>
                    </a>
                    <small>(<%=apartment.rent%>)</small>
                    <small>(<%=apartment.location%>)</small>
                </li>
                <%})%>
        </ul>
        <%}%>
```

**Comment by isaac8069** [comment]
<img width="629" alt="Screen Shot 2021-11-17 at 4 21 13 PM" src="https://user-images.githubusercontent.com/90520586/142284286-2794f882-c1a6-4de3-915f-a64e413efc65.png">

I have the correct url! I don't know why its not hitting the correct route

**Comment by isaac8069** [comment]
**Three things I've tried:**
1. I tried changing the url around in my apartment.js controller
2. I checked my result.ejs and index.ejs
3. I reformatted the GET route for my search
Error Message: Cannot GET /apartments/search

**Comment by DoireannJane** [comment]
I'm looking at your .render. Is your result.ejs within apartments in your directory structure?

**Comment by isaac8069** [comment]
When you say directory structure what are you referring to?

**Comment by DoireannJane** [comment]
Your folders and files in your app.

**Comment by DoireannJane** [comment]
Your .render should be rendering an .ejs file in your views.

**Comment by isaac8069** [comment]
Yes, result.ejs is within my apartments directory structure
<img width="210" alt="Screen Shot 2021-11-18 at 10 18 38 AM" src="https://user-images.githubusercontent.com/90520586/142443318-6600150d-9e2b-44d1-adae-1a46478fe3da.png">
.

**Comment by DoireannJane** [comment]
In your controllers middleware, are you requiring the apartments url path?

**Comment by isaac8069** [comment]
<img width="700" alt="Screen Shot 2021-11-18 at 10 27 03 AM" src="https://user-images.githubusercontent.com/90520586/142444819-e71d67f0-00c3-4166-9534-43bfb76986d0.png">
Yes, I am requiring the apartments url path

**Comment by DoireannJane** [comment]
Your controllers middleware should be in your index.js

**Comment by isaac8069** [comment]
The console log is bringing up another routes console log. When I comment the route out it brings up the search console log message. Not sure why. They have different URLs

**Comment by DoireannJane** [comment]
I was looking for the middleware. App.use

**Comment by DoireannJane** [comment]
Your GET route looks fine.

**Comment by DoireannJane** [comment]
Could you show me the middleware? Should look like this: TAYLOR'S SNIPPET BELOW

**Comment by isaac8069** [comment]
I do not have that in my middleware.

**Comment by TaylorDarneille** [comment]
Actually the middleware should say `app.use('/apartments', require('./controllers/apartments'))`.  If your current middleware is showing a singular `/apartment`, then it means that the action on your search form is wrong and should be `/apartment` (currently it's showing `/apartments`)

**Comment by isaac8069** [comment]
<img width="1089" alt="Screen Shot 2021-11-18 at 1 46 01 PM" src="https://user-images.githubusercontent.com/90520586/142477567-1d5116ae-fb5f-4039-9b90-9bd83feae462.png">
Thats what I have

**Comment by isaac8069** [comment]
<img width="1167" alt="Screen Shot 2021-11-18 at 1 47 01 PM" src="https://user-images.githubusercontent.com/90520586/142477698-b4af0d3f-7d34-49c8-b7c7-6ce0bea0e2be.png">
This is my form! It matches my controller in index.js

**Comment by TaylorDarneille** [comment]
resolved!
