### ISSUE TITLE
can not get my notes to render

### ISSUE THREAD

**Issue by anaismveras** [WDI-SEA/project-2-issues#55]
my notes go into the db but I try to show them on the page it doesnt show
```js
router.get('/:animal_id/comments', isLoggedIn, (req, res)=> {
    db.note.findAll({
        where: {userId: res.locals.currentUser.id}
    })
    .then(note => {
        console.log('this is note', note)
        res.render('animalDetail', {note: note})
    })
})

router.post('/:animal_id/comments', isLoggedIn, (req, res) => {
    console.log('this is req.body', req.body)
    db.note.create({
        favePetId: req.params.animal_id,
        userId: res.locals.currentUser.id,
        description:req.body.description
    })
    .then(resPost => {
        console.log('this is resPost', resPost)
        res.redirect(`/profile/${req.params.animal_id}`)
    })
    .catch(error => {
        console.log(error)
        res.send('invalid comment', error)
    })
})

<% note.forEach(function(comments) { %>
    <p><%= comments.descrption  %> </p>
<% }) %> 
```

error says note is not defined but it is in the router.get

**Comment by tkolsrud** [comment]
are you getting anything from the console.log?

**Comment by anaismveras** [comment]
I am not getting anything from the console.log...I tried a new approach and I undo migrated the notes table to add a favepetId because it kept telling me that note and FavePet were not associated but now favePetId comes back null in the db

**Comment by tkolsrud** [comment]
Can i see the form/inputs you're using to add the favPet

**Comment by anaismveras** [comment]
i put a the db.note.findAll inside the router.get of the '/:animal_id' it renders on the page but only one comment shows up but technically it works

**Comment by TaylorDarneille** [comment]
closing since you opened another :)
