### ISSUE TITLE
delete button/redirect from faves not working

### ISSUE THREAD

**Issue by hannahlegros** [WDI-SEA/project-2-issues#57]
my delete button doesn't work and i have my favorites set up as link that will take you to the recipe page, which is also not working. Think they may be a similar issue.. 
this is the link to go to the recipe page and the delete button form (mydrinks.ejs)
```<% myDrinks.forEach(drink => { %>
    <h4>
        <a href="/drinksByName/<%= drink.idDrink %>"><%= drink.name %></a>
    </h4>
    <form action="/myDrinks/<%= drink.idDrink %>?_method=DELETE" method="POST">
        <button type="submit">remove</button>
    </form>
<% }) %>

**Comment by hannahlegros** [comment]
this is my delete route (myDrinks.js)
```router.delete('/:id', (req, res) => {
    console.log('this is the id: ', req.params.id)
    db.recipe.destroy({
        where: {idDrink: req.params.id}
    })
    .then(deletedItem => {
        console.log('you deleted: ', deletedItem)
        res.redirect('/myDrinks')
    })
    .catch(error =>{
        console.log(error)
    })
})

**Comment by hannahlegros** [comment]
i tried changing the route MULTIPLE times and the URL pattern for the link, but i keep getting the same error in the browser.. 
for the link the error is : Cannot GET /drinksByName/ (with only a 404 in the dev tools console)
for the delete button the error is: Cannot DELETE /myDrinks/ (also a 404 and my console logs are not showing anywhere)

**Comment by shuzel99** [comment]
you might need to require method override and try again. this happened to me

`const methodOverride = require('method-override')

//allows you to use put and delete
app.use(methodOverride('_method'))`

I put that in my index.js after doing npm install method-override

**Comment by hannahlegros** [comment]
i do have that in my app, but thank you!!

**Comment by tkolsrud** [comment]
Were you able to get this one resolved?

**Comment by TaylorDarneille** [comment]
Resolved and back on track :) Going to let the user edit their name to meet update requirement.
