### ISSUE TITLE
Cannot read property 'findOne' of undefined

### ISSUE THREAD

**Issue by Ramon-Carrillo** [WDI-SEA/project-2-issues#6]
I am not sure if my models are set up correctly. I am using postman to check my routes. Right now I am getting an error Cannot read property 'findOne' of undefined.

**Comment by tkolsrud** [comment]
can you post the error/codeblock?

**Comment by Ramon-Carrillo** [comment]
I am not even sure where to start.

**Comment by Ramon-Carrillo** [comment]
`const express = require('express');
const router = express.Router();
const bcrypt = require('bcryptjs');
const { body, validationResult } = require('express-validator');

const user = require('../models/user');

// route: Post api/users
// desc: register users
//access: Public
router.post(
  '/',
  [
    body('userName', 'User name is required').not().isEmpty(),
    body('password', 'Password is required minimum 8 characters').isLength({ min: 8 }),
  ],
  async (req, res) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({ errors: errors.array() });
    }
    const { userName, password } = req.body;

    try {
      let user = await user.findOne({ where: { userName } });

      if (user) {
        return res.status(400).json({ msg: 'User name already exists' });
      }

      user = new User({
        userName,
        password,
      });
      const salt = await bcrypt.genSalt(10);
      user.password = await bcrypt.hash(password, salt);

      await user.save();
      res.send('user saved');
    } catch (err) {
      console.error(err.message);
      res.status(500).send('Server Error');
    }
  },
);
`

**Comment by DoireannJane** [comment]
Your User is a model so it should be capitalized before .findOne()

**Comment by Ramon-Carrillo** [comment]
'use strict';
const { Model } = require('sequelize');
module.exports = (sequelize, DataTypes) => {
  class user extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      // define association here
    }
  }
  user.init(
    {
      userName: DataTypes.STRING,
      password: DataTypes.STRING,
    },
    {
      sequelize,
      modelName: 'user',
    },
  );
  return user;
};

**Comment by Ramon-Carrillo** [comment]
![Screenshot from 2021-11-15 10-35-57](https://user-images.githubusercontent.com/68085268/141819326-0398f10f-69ef-45d9-8364-678bad616be4.png)

**Comment by Ramon-Carrillo** [comment]
This is what happens when I have user as User

**Comment by DoireannJane** [comment]
So Tim or Taylor should circle back with you for this issue since you're going a different auth route. Also just a reminder to commit and commit often!

**Comment by TaylorDarneille** [comment]
resolved :)
