### ISSUE TITLE
My Post Route is crashing out

### ISSUE THREAD

**Issue by isaac8069** [WDI-SEA/project-2-issues#62]
I had to do an undo all migration. I re-migrated and started to add back users and apartment listings. After I hitting submit, I'm getting the error message: ERR_HTTP_INVALID_STATUS_CODE . It is creating the listing which I can see on my All Listings page and in the database, but the redirect isn't functioning properly anymore. I have looked at my routes, views, and index.js. I can't seem to find the problem. I researched the error message as well. The suggestions I found was to add an error status to my app.get middleware . However, I don't think that is the appropriate solution as I did not have that prior to migration. It seemed to work just fine. Please see the screenshots below:

<img width="762" alt="Screen Shot 2021-11-18 at 12 40 43 PM" src="https://user-images.githubusercontent.com/90520586/142468997-c11993d4-0a4b-4f03-a295-dec44bf30773.png">

<img width="1148" alt="Screen Shot 2021-11-18 at 12 47 43 PM" src="https://user-images.githubusercontent.com/90520586/142469101-c2999929-9f4d-46af-9e1b-018ebb551f7e.png">

**Comment by TaylorDarneille** [comment]
Do you have a status code attached to the res.render or res.redirect that occurs just before you hit this? The error sounds like it doesn't like. Try removing it?

**Comment by TaylorDarneille** [comment]
I'm also noticing the "Invalid status code: {apartment: [apartment] }" .... sound like you have that code inside of a res.status?

**Comment by isaac8069** [comment]
<img width="656" alt="Screen Shot 2021-11-18 at 1 36 41 PM" src="https://user-images.githubusercontent.com/90520586/142476333-a1054ed7-3a48-4f0f-9668-4986639f8817.png">

**Comment by TaylorDarneille** [comment]
fixed redirect
