### ISSUE TITLE
.belongsToMany error

### ISSUE THREAD

**Issue by emilybarwinczak** [WDI-SEA/project-2-issues#63]
![image](https://user-images.githubusercontent.com/92114356/142477596-78df2429-ba56-47d5-9aa3-5cad60e6aa56.png)

Not sure what's wrong with my tables

**Comment by TaylorDarneille** [comment]
I don't think there is anything wrong with your tables, but instead how you set up the associations. Can I see your post model associations?

**Comment by emilybarwinczak** [comment]
sure, should we meet in a break out room?

**Comment by emilybarwinczak** [comment]
extra s on one of the tags
