### ISSUE TITLE
I can't update my map with DB data because it is rendered inside of a script in an ejs page.

### ISSUE THREAD

**Issue by hectorzaragoza** [WDI-SEA/project-2-issues#65]
This is where the issue is:

I am rendering my map on DOMContentLoaded inside of JS script tags in an ejs file. So, I can't access the database data that I'm passing from the controller to the view in the JS script.

This the code that lives inside my ejs view: 
![image](https://user-images.githubusercontent.com/62188104/142494942-1e6833ba-f29d-4260-8a02-71a1e0672e33.png)

I have tried:
1) using the data I pass to the view from the controller inside the JS script but nothing happens.
2) The data shows up if I use ejs syntax outside of the JS script.
3) I tried moving the map rendering into the controller but the client-side functionality (document, navigator) don't work.

**Comment by timmshinbone** [comment]
Still working on this? if so, update on what's been tried, if not add solution and close it

**Comment by hectorzaragoza** [comment]
I was fixing the earlier issue. I am going to tackle this now. Goro gave me some suggestions to try.

**Comment by hectorzaragoza** [comment]
Goro to the rescue!
