### ISSUE TITLE
Terminal error after editing models

### ISSUE THREAD

**Issue by Eddycodes27** [WDI-SEA/project-2-issues#66]
Working on logging information onto a page. Need to edit models so they work with each other, but unable to do so due to error. images attached.
![Screen Shot 2021-11-18 at 4 23 26 PM](https://user-images.githubusercontent.com/91762173/142498901-fa29e949-3ae2-4d8d-af81-b2e4d8f65994.png)
![Screen Shot 2021-11-18 at 4 24 13 PM](https://user-images.githubusercontent.com/91762173/142499010-00d91eac-cb78-4e36-85a9-0f45c26d0a7e.png)
![Screen Shot 2021-11-18 at 4 24 50 PM](https://user-images.githubusercontent.com/91762173/142499101-7eb5476b-6145-47cc-9435-2f0ecb1daacb.png)
![Screen Shot 2021-11-18 at 4 25 49 PM](https://user-images.githubusercontent.com/91762173/142499213-bb5cca42-40b6-4d26-88da-5db7836409b0.png)

**Comment by tkolsrud** [comment]
So we saw this one earlier, its likely a type somewhere in your models/migration files. Is everything in agreement in terms of pluralization and capitalization?

**Comment by Eddycodes27** [comment]
No, that didn't work :-(

**Comment by DoireannJane** [comment]
Hi Eddy! You might have to delete your migrations all together and re-migrate your models.

**Comment by DoireannJane** [comment]
Let's pop in a breakout room in a bit.

**Comment by Eddycodes27** [comment]
I deleted all migrations and logs that had to be redone. Timm guided me to DROPping the database in psql. I then recreated the database, made the attributes, and then migrated once more.
