### ISSUE TITLE
Issue creating a comment: Error - invalid input syntax for type integer: "Hector"

### ISSUE THREAD

**Issue by hectorzaragoza** [WDI-SEA/project-2-issues#72]
The issue: When creating a comment with input from a form, the system takes the name field and tries to store it in db where the type is integer. I'm assuming that db column is the id of the comment table.

I think the issue may be in how my model is set up. The associations seem to be ok. 
View
![image](https://user-images.githubusercontent.com/62188104/142656364-8a33a518-46e5-49c6-8408-53ecf21f47a7.png)
Router
![image](https://user-images.githubusercontent.com/62188104/142656436-417728ac-be71-41c0-9beb-10e15de927df.png)
Model
![image](https://user-images.githubusercontent.com/62188104/142656551-fef04369-a5a0-4323-9e29-6ff2a361f11f.png)

I've tried:
1) double checking my associations, the table
2) tried creating an id in the db.comment.create method but it says the same error for the next field.

**Comment by tkolsrud** [comment]
What does the column say in the actual database?

**Comment by hectorzaragoza** [comment]
integer...

The models and Migrations are all set up correctly so I don't understand why the DB would have something different.
