### ISSUE TITLE
on user profile its grabbing from allusers db

### ISSUE THREAD

**Issue by kellylarrea** [WDI-SEA/project-2-issues#73]
After changing my models I'm still a little confused as to where to grab and if there is any associated needed to populate correct data to correct tables

Currently I have one item rendering from my table to my favorites but it's grabbing from all users. 

I'm using 

```<a href="<%=recipe.ketoRecipeUrl%>" target="_blank"><%=recipe.ketoRecipeLabel%></a>```

Currently there is no association with my models so I'm wondering if that's correct.

**Comment by tkolsrud** [comment]
The favorites table has a userId column right?

**Comment by kellylarrea** [comment]
Yes. I was able to render from the current user! 

I used 

```router.get('/', (req, res)=>{
    db.userKetoRecipe.findAll({
        where: {userId: res.locals.currentUser.id}
    })
        .then(foundUser =>{
    res.render('profile', {foundUser})
    // console.log(recipe)
    })
})```
Just would like some clarification on what to do with the other tables I have since I feel like I wont be needing ketoRecipes table for example?

**Comment by tkolsrud** [comment]
Ahhhh, yeah you really just need your user, and then the userrecipe tables, since the api is providing the data for your keto/paleo recipdes

**Comment by kellylarrea** [comment]
Awesome just wanted to make sure. Thank you!
