### ISSUE TITLE
Game description has html tags in it. 

### ISSUE THREAD

**Issue by DG-98** [WDI-SEA/project-2-issues#9]
This is my code block for calling the descrpitions of the game but when its displayed there are <p> tags all over. Might be an api thing but im not sure how to solve it. 
```router.get("/:game_id", function(req, res){
  let rawgId = req.params.game_id 

  axios.get(
    `https://api.rawg.io/api/games/${rawgId}?key=${process.env.RAWG_KEY}`
  )
  .then((apiRes)=>{
    console.log(apiRes.data.name)
    let name = apiRes.data.name
    let description = apiRes.data.description
    let released = apiRes.data.released 
    let background_image = apiRes.data.background_image
    let metacritic = apiRes.data.metacritic

    res.render("detail", {
      name: name,
      description: description,
      released: released,
      background_image: background_image,
      metacritic: metacritic,
    })
  })
  .catch((err) => {
      console.log(err)
  })
})

**Comment by DG-98** [comment]
example of description 
![image](https://user-images.githubusercontent.com/85405879/141824850-81673581-7336-4ffb-80be-1e59ea0b8b53.png)

**Comment by tkolsrud** [comment]
That is in fact an api thing. You might have to write a function that searches for p tags and then slices them out before rendering. Let us know if you want to go into a breakout room and work on it 1:1

**Comment by TaylorDarneille** [comment]
closing this because we talked about strategies for it
